import SWRConfigContext from "@/context/SWRConfigContext";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <SWRConfigContext>
        <body className="mx-12">{children}</body>
      </SWRConfigContext>
    </html>
  );
}
